### ISSUE TITLE
SubsiteAdminExtension class name collision

### ISSUE THREAD

**Issue by michalkleiner** [lekoala/silverstripe-subsites-extras#5]
The SubsiteAdminExtension class also exists in https://github.com/adrexia/silverstripe-subsite-modeladmins, making it difficult to use both modules at the same time.

I can submit a PR namespacing all the extension classes if you suggest what namespace you'd like to use.

**Comment by lekoala** [comment]
given the very small scope of the other module, it would be better to simply integrate the functionnalities into my module.

but otherwise it could be renamed to something like SubsiteAdminBetterButtonsExtension because it's really simply to fix the backlink for better buttons (i'm not even sure it's still an issue, it created this a while ago)

**Comment by michalkleiner** [comment]
Yep, that'd work too. Rename the extension class fixing the BetterButtons issue and add Adrexia's functionality. Then, we could only use this module, covering all we need :-)

**Comment by lekoala** [comment]
feel free to make a pull request, i'd happily merge :)

**Comment by lekoala** [comment]
meanwhile i've renamed the class :)
